name: test-harry-potter
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with: 
        channel: stable
        flutter-version-file: pubspec.yaml
        cache: true
    - run: flutter test -r json > test-results.json
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Flutter Tests
        reporter: flutter-json
        path: test-results.json